antha/AnthaStandardLibrary/Packages/enzymes/Ligation.go
antha/anthalib/wtype/annotatedsequence.go
antha/anthalib/wtype/biology.go

Change free form to lower case with _ word separation for:
- Assemblyparameters
- DNASequence
- Feature
- Overhang

Normalise json field names

---

microArch/scheduler/liquidhandling/lhrequest.go

Allow seriali(z/s)ation of LHRequest

allow serialization of LHRequest

---

target/mixer/mixer.go
target/mixer/opt.go

pass tip preferences

---

cmd/antharun/pretty/timeline.go
target/inst.go
target/mixer/mixer.go

related to same branch in microArch

flatten inst hierarchy

---

antha/anthalib/wtype/wellcoords.go
antha/anthalib/wtype/wtype_test.go
microArch/scheduler/liquidhandling/executionhelpers.go

fixed missing return statement in instruction sort. Should mean we have default columnwise ordering of execution in line with other defaults

Order determinism

---

antha/AnthaStandardLibrary/Packages/doe/doe.go
antha/anthalib/wtype/lhtypes.go
driver/lh/client.go
driver/lh/lh.proto
driver/pb/lh/lh.pb.go
microArch/driver/liquidhandling/choosechannel_test.go
microArch/driver/liquidhandling/compositerobotinstruction.go
microArch/driver/liquidhandling/lhpolicy.go
microArch/driver/liquidhandling/makelhpolicy.go
microArch/scheduler/liquidhandling/layoutagent2.go
microArch/scheduler/liquidhandling/liquidhandler.go
microArch/scheduler/liquidhandling/make_liquidhandler.go
microArch/scheduler/liquidhandling/setupagent.go

Update to allow platform-specific rules to function... required a change to driver so tests will fail until all are merged in 
depends on platformrefactor branches in all drivers (manual, cybio, pipetmax)

Platformrefactor

---

antha/anthalib/wunit/serialize.go

serialize values too

---

microArch/factory/make_plate_library.go

Fixed issue where the Pipetmax head would collide with the plate when aspirating

fixed height issue with DWST12 to avoid coliison with pipettehead

---

antha/anthalib/mixer/mixer.go
antha/anthalib/wtype/lhcomponent.go
antha/anthalib/wtype/lhtipbox.go
antha/anthalib/wtype/lhtipwaste.go
antha/component/an/Liquid_handling/TypeIIsAssembly/TypeIISConstructAssemblyMMX/TypeIISConstructAssemblyMMX.an
antha/component/an/Liquid_handling/TypeIIsAssembly/TypeIISConstructAssemblyMMX_forscreen/TypeIISConstructAssemblyMMX.an
antha/component/lib/TypeIISConstructAssemblyMMX_.go
antha/component/lib/TypeIISConstructAssemblyMMX_forscreen_.go
execute/intrinsics.go
microArch/scheduler/liquidhandling/input_plate_setup.go
microArch/scheduler/liquidhandling/liquidhandler.go
microArch/scheduler/liquidhandling/liquidhandling_test.go
microArch/scheduler/liquidhandling/refresh_tipboxes.go
microArch/scheduler/liquidhandling/setupagent.go
microArch/scheduler/liquidhandling/tip_box_setup.go

Various modifications to ensure correct state tracking through planner

Fix volumes

---

antha/anthalib/mixer/mixer.go
antha/anthalib/wtype/lhinstruction.go
antha/compile/antha.go
execute/intrinsics.go
microArch/scheduler/liquidhandling/layoutagent2.go
microArch/scheduler/liquidhandling/liquidhandler.go

Proposed mechanism for allowing users to mix to a named plate

Added MixNamed command... will eventually replace MixTo

---

antha/anthalib/wtype/lhplate.go
microArch/driver/liquidhandling/compositerobotinstruction.go
microArch/driver/liquidhandling/lhl_test.go
microArch/driver/liquidhandling/lhproperties.go
microArch/driver/liquidhandling/makelhpolicy.go
microArch/scheduler/liquidhandling/liquidhandler.go

Several fixes to some rather hasty additions... will merge immediately if tests pass

Pickup vol fix

---

antha/anthalib/wtype/lhcomponent.go
execute/intrinsics.go
microArch/scheduler/liquidhandling/determinism_test.go
microArch/scheduler/liquidhandling/liquidhandler.go

final component volumes should be correct now

Remove duplicate mix

---

codegen/codegen.go
graph/eliminate.go

Reduce memory of node elimination by simplifying graph first. Also, support arbitrary elimination orders.

Mem eliminate

---

microArch/driver/liquidhandling/makelhpolicy.go
microArch/factory/make_plate_library.go

48 well plate added and physically tested
previous changes (removal of postmix replicate volume and addition of SRFWB96 incubator height) are from previous pull request, sorry

48wellplate added

---

microArch/factory/make_plate_library.go

Fixed heights for 48 well plate on qinstruments incubator
Fixed heights for 12 well plate on qinstruments incubator

Dowcorrectincubatorheight

---

microArch/factory/make_plate_library.go

Changed the Nunc incubator height as crashing now - this will fix, and need to put to master to rebuild monolith

updated plate height nunc 12 well incubator -5 to -2.5

---

microArch/factory/make_plate_library.go

Updated final plate height for uncon 12 well on incubator, this is the final version

final final plate height for incubator

---

microArch/scheduler/liquidhandling/setupagent.go

prevent duplicate addition of plates

---

antha/anthalib/wtype/lhplate.go
antha/anthalib/wtype/lhwell.go
cmd/antharun/cmd/lhcomponents.go
cmd/antharun/cmd/lhpolicies.go
cmd/antharun/cmd/plates.go
microArch/driver/liquidhandling/lhpolicy.go

Could expand to include additional flags to return properties of specific plates and policies

Added commands to antharun to list LHComponents, LHPlates and LHPolicies 

---

antha/component/an/Utility/PlateHeightTest.an
antha/component/an/Utility/PlateHeightTest3.an
antha/component/lib/PlateTest3_.go
antha/component/lib/PlateTest_.go
antha/examples/workflows/PlateHeightTest/Arnoldpcrplateskirted20161117160504.csv
antha/examples/workflows/PlateHeightTest/parameters.yml
antha/examples/workflows/PlateHeightTest/report20161117165242.md
microArch/driver/liquidhandling/compositerobotinstruction.go
microArch/driver/liquidhandling/makelhpolicy.go
microArch/factory/make_plate_library.go

Modified the priority of the HV offset policy, made contingent on tip and platform, consequence is now an-offset-to-an-offset

Investigate hv offset

---

antha/anthalib/setup/setup.go
antha/anthalib/shakeincubate/shakeincubate.go

Handle refactor; 
Dependent PR in Synthace/elements

Setuptemprefactor

---

antha/component/an/AnthaAcademy/Lesson5_Units2/B_MasstoVolume.an
antha/component/an/GrowthAndAssay/default.an
antha/component/lib/GrowthAndAssay_.go
antha/component/lib/MasstoVolume_.go
cmd/antha/antha.go

check for duplicate protocols when generating too

---

antha/compile/antha.go
execute/execute.go
execute/executeutil/test.go
execute/resolver.go
execute/resolver_test.go
inject/inject_test.go
inject/injectutil/injectutil_test.go
inject/remote/remote_test.go
inject/runner.go
peanut.yml
trace/pool.go
trace/resolve.go
trace/trace.go
trace/trace_test.go
workflow/workflow.go
workflow/workflow_test.go

Mutually dependent with:
- antha-lang/elements#18
- Synthace/elements#50

use go17 context

---

codegen/codegen.go
codegen/normalize.go
graph/graph.go
graph/reaches.go
graph/reaches_test.go

Reduce memory usage by calculating simpler node reachability versus eliminating nodes.

Reaches for eliminate

---

cmd/antharun/cmd/new_element.go

Replacement for:
- antha-lang/antha#230

new element command

---

antha/anthalib/wtype/lhplate.go
microArch/driver/liquidhandling/lhproperties.go

reinstated residual volume accounting in GetComponent

fixed missing rvol

---

antha/compile/antha.go

wtype will be automatically included (if missing) in generated go code by antha.
cc @chr1sgrant

add import wtype in generated go if missing

---

antha/anthalib/wtype/lhcomponent.go

Unmarshaling interface{} converts ints to floats

check for generic serialization case

---

microArch/factory/make_component_library.go

Added this in since we have started using mastermix for BsaI. Simulated using the Aliquot protocol, all works.

added lhcomponent for mastermix_bsai

---

cmd/antharun/spawn/spawn.go

go18 url parsing is too strict

---

antha/AnthaStandardLibrary/Packages/export/export.go

Fasta files were not being correctly exported into wtype.File. This PR should fix this issue.

fix export fasta functions

---

microArch/scheduler/liquidhandling/layoutagent2.go
microArch/scheduler/liquidhandling/liquidhandler.go
microArch/scheduler/liquidhandling/newexecutionplanner.go

Additional output plates were being created unnecessarily... this fixes the problem

Plate ID Remapping added to name map

---

microArch/factory/make_plate_library.go

Tested with plate height test:
-Low volume aspirating/dispensing OK
-High volume aspirating/dispensing OK

New plate/eppi lid clip

---

antha/AnthaStandardLibrary/Packages/enzymes/Assemblydesign.go

added additional MoClo custom overhangs

---

README.md

necessary additions to PATH missing in linux setup
location of test protocol updated

Add missing steps to Linux and correct path in test

---

antha/AnthaStandardLibrary/Packages/download/urltofile.go

Revert "Getting URLtofile to use wtype.File"

---

antha/anthalib/wunit/wdimension.go
antha/anthalib/wunit/wunit_test.go
microArch/factory/make_component_library.go

Adding liquid component Gibson Master Mix and handling basic functions for adding/subtracting concentrations.

Add gibson mastermix to factory

---

microArch/factory/make_plate_library.go

Verified with plate tests and accuracy test

added riser18

---

antha/anthalib/wtype/biology.go

Revert "fix serialization of DNASequence.Nm"

---

codegen/normalize.go
execute/context.go
execute/error.go
execute/execute.go
execute/intrinsics.go
execute/maker.go
execute/params.go
execute/resolver_test.go
graph/dag.go
target/human/human.go
target/target.go

Eliminate is quadratic, so avoid if possible.
Ready to review.

target/human: avoid graph.Eliminate

---

microArch/scheduler/liquidhandling/executionhelpers.go
microArch/scheduler/liquidhandling/liquidhandler.go

Added missing volume override

---

microArch/scheduler/liquidhandling/executionhelpers.go
microArch/scheduler/liquidhandling/liquidhandler.go

Proposed fix for Synthace/AnthaUI#1464

Prevent outputs in input plates getting squashed

---

microArch/scheduler/liquidhandling/liquidhandler.go

... which they previously were

Ensure non-Mix instructions are not treated as dummies

---

antha/anthalib/wtype/lhcomponent.go
antha/anthalib/wtype/lhplate.go
antha/anthalib/wtype/lhtip.go
antha/anthalib/wtype/lhtipbox.go
antha/anthalib/wtype/lhtipwaste.go
antha/anthalib/wtype/lhwell.go
antha/anthalib/wtype/wtype.go
microArch/scheduler/liquidhandling/liquidhandler.go

Reverts antha-lang/antha#472  --- upstream changes in antha runner are required

Revert "Fix/wastes in after states"

---

antha/AnthaStandardLibrary/Packages/sequences/annotatedseq.go
antha/AnthaStandardLibrary/Packages/sequences/findSeq.go
antha/AnthaStandardLibrary/Packages/sequences/parse/genbank/genbankparser_test.go
antha/anthalib/wtype/annotatedsequence.go

Makes []PositionPair implement sort interface.
Adds unified Coordinate methods for Position Pairs and Features.
refactors MakeAnnotatedSequence to use more robust FindSeq func

Refactor find seqs in seqs

---

microArch/scheduler/liquidhandling/liquidhandler.go
target/mixer/mixer.go

Plates added from protocols were not added in line with those added as config items... this PR rectifies the discrepancy

Input plates from protocols now added correctly

---

antha/anthalib/wtype/lhplate.go
microArch/driver/liquidhandling/getComponents.go
microArch/driver/liquidhandling/transferblock.go

Revert "Inflate sources reported to allow for multichannelling"

---

antha/anthalib/wtype/componentvector.go
antha/anthalib/wtype/lhplate.go
antha/anthalib/wtype/lhtip.go
antha/anthalib/wtype/lhtipbox.go
microArch/driver/liquidhandling/convertinstructions.go
microArch/driver/liquidhandling/getComponents.go
microArch/driver/liquidhandling/lhproperties.go
microArch/driver/liquidhandling/parallelset_test.go
microArch/driver/liquidhandling/transferblock.go
microArch/driver/liquidhandling/transferblock_test.go
microArch/driver/liquidhandling/transferinstruction.go

This allows different treatment for transfers which will eventually be multi'd in terms of getting sources and atomic mixes
There may still be residual issues in cases where atomic and non-atomic mixes are combined.

Lookahead for multichanneling

---

microArch/scheduler/liquidhandling/lhrequest.go
microArch/scheduler/liquidhandling/liquidhandler.go

Initial response to 
https://app.asana.com/0/475382186313932/498781036457375/f

Assert: mix-volume <= well-capacity

---

inventory/testinventory/make_plate_library.go

@chr1sgrant Change here - no chance to physically test yet, but without something like this, the plate will 100% crash.

update zoffset of SRWFB plate, no physical testing

---

cmd/antha/cmd/run.go

Command-line usage segfaults without this fix

Add check when mock devices are missing

---

inventory/testinventory/devices.go
inventory/testinventory/make_plate_library.go
inventory/testinventory/make_plate_library_test.go

Depends on:
https://github.com/antha-lang/antha/pull/645
https://github.com/antha-lang/antha/pull/640
https://github.com/antha-lang/antha/pull/639
Testing documents here:
https://www.dropbox.com/sh/h6irbjcc2c4qa17/AACESbfh01-1_GV1I9KPpQMAa?dl=0

New riser/mag bead plate

---

inventory/testinventory/make_plate_library.go

Testing files documented here:
https://www.dropbox.com/s/skklcqm0xanu1hb/Thermo_96_deepwell_1ml.docx?dl=0
https://www.dropbox.com/s/n8opkuur49mu4p6/Thermo_96_deepwell_1ml20180226143140.csv?dl=0

New plate/deep well96 1ml

---

antha/AnthaStandardLibrary/Packages/doe/handlefactortypes.go

Fixes two element CI test failures.

relax strict equality requirement when checking for UnknownType error

---

microArch/driver/liquidhandling/compositerobotinstruction.go
microArch/driver/liquidhandling/makelhpolicy.go

Override mixvolume when using filter tips

---

ast/qpcrinstruction.go
execute/intrinsics.go
target/qpcrdevice/qpcrdevice.go

Allow support for job id insertion.
Use multiple input LHC elements.
Clean ups to functionality and messaging

Additional work for base qPCR driver

---

antha/anthalib/wtype/lhplate.go
inventory/testinventory/make_plate_library.go
microArch/driver/liquidhandling/getComponents.go
microArch/scheduler/liquidhandling/input_plate_linear.go
microArch/scheduler/liquidhandling/layoutagent2.go

Revert "Fix/plate id generic types"

---

antha/anthalib/wtype/lhplate.go
inventory/testinventory/make_plate_library.go
microArch/driver/liquidhandling/getComponents.go
microArch/scheduler/liquidhandling/input_plate_linear.go
microArch/scheduler/liquidhandling/layoutagent2.go

Revert "Revert "Revert "Fix/plate id generic types"""

---

antha/anthalib/wtype/lhwell.go

otherwise you can't take 200ul from a 200ul well

Wells can hold MaxVolume plus ResidualVOlume

---

microArch/scheduler/liquidhandling/liquidhandler.go

https://synthace.atlassian.net/browse/ANTHA-1170

more human readable errors

---

inventory/testinventory/make_tip_library.go

As per lab testing by charlotte

Add 0.75mm to the effective height of each gilson filter tip

---

antha/AnthaStandardLibrary/Packages/doe/doe_test.go
antha/AnthaStandardLibrary/Packages/doe/handlefactortypes.go
antha/anthalib/wunit/unitfromstring.go
antha/anthalib/wunit/unitfromstring_test.go

Fixes CI tests relating to parsing concentrations.

more robust handling of concentrations in headers

---

microArch/simulator/liquidhandling/simulator.go

Fixes the ton of spurious overfull well warnings that charlotte was seeing

Reduce the dispensed volume to the volume in the tip on blowout

---

antha/anthalib/wtype/lhplate.go

quick fix to avoid LLF causing panic in the simulator

Return well bottom for LiquidLevel

---

antha/anthalib/wtype/lhinstruction.go
microArch/scheduler/liquidhandling/liquidhandling_test.go

unit tests for multichannel split sample

---

antha/anthalib/wtype/lhtipbox.go
antha/anthalib/wtype/lhtypes.go
driver/lh/helpers.go
microArch/driver/liquidhandling/getComponents.go
microArch/driver/liquidhandling/tipswellsaligned.go
microArch/simulator/liquidhandling/robotstate_test.go
microArch/simulator/liquidhandling/simulator_test.go
microArch/simulator/liquidhandling/simulator_testcode_test.go

previously these existed as plain ints, added a type to enable type checking

Make wtype.LHVChannel and wtype.LHHChannel of type wtype.ChannelOrientation

---

target/auto/mock.go
target/woplatereader/woplatereader.go

Tests pass, but with antha-runner you need the same branch in there too.

[ANTHA-2033] Rename. WOOOOOOOOOOOOOOOOOO!

---

ast/qpcrinstruction.go
target/auto/mock.go
target/qpcrdevice/qpcrdevice.go
target/woplatereader/woplatereader.go

I'm going to need some help figuring out how to test this best - there is 0% code coverage from both local tests and antha-tester tests. Seems like some integration tests in the latter would be useful. Any ideas?

[ANTHA-2073] Simplify QPCR support.

---

antha/anthalib/wtype/lhinstruction.go

local tests still pass. antha-runner still builds. Just waiting for antha-tester tests to complete... :yawn:

LHInstruction.Order is not used. Deleting.

---

antha/anthalib/wtype/lhinstruction.go
microArch/scheduler/liquidhandling/ichain.go

local tests pass. Just waiting on antha-tester...

Turns out SName isn't used either.

---

antha/anthalib/wunit/parse.go
antha/anthalib/wunit/serialize.go
antha/anthalib/wunit/serialize_test.go
antha/anthalib/wunit/unitfromstring_test.go
antha/anthalib/wunit/wunit.go

fixes JSONification of concentrations with units which contain strings, e.g. "% w/v"

[Antha-2113] % w/v volume fix

---

antha/AnthaStandardLibrary/Packages/platereader/Platereader.go
antha/AnthaStandardLibrary/Packages/platereader/dataset/interface.go
antha/AnthaStandardLibrary/Packages/platereader/dataset/mars.go
antha/AnthaStandardLibrary/Packages/platereader/dataset/spectramax.go
antha/anthalib/wtype/absorbance.go

This change adds a more general method to the AbsorbanceData definition which returns all absorbance data in a generic format with all absorbance data returned for all wells.

All absorbance data

---

execute/executeutil/unmarshal.go

Slight change to unmarshalling of bundles to help with antha-runner/testbundles.
Does not affect antha-tester - behaviour of antha-tester before and after is the same.

bundle unmarshalling non-bundle is not an error.

---

execute/executeutil/unmarshal.go

Previously, we were trying to unmarshal into a Bundle object. If that failed, we claimed it wasn't a valid json file. But this is not correct - an array is a valid json file, but because a bundle is an object, it won't unmarshal.
So if we unmarshal to json.RawMessage first then it just checks it's valid json.
This is related to antha-runner PR370

Be more accurate about labelling a file as "not json".

---

ast/ast.go
codegen/codegen.go

Test Plan:
suitably set up antha-runner testbundles passes. That said, I'm not 100% sure if our test bundles would check tasks across different devices.

Turns out that ast.Move is dead code and there's quite a lot of code that goes out with it

---

microArch/scheduler/liquidhandling/liquidhandler.go

Policy Manager isn't used here.

---

microArch/driver/liquidhandling/lhproperties.go
microArch/driver/liquidhandling/lhproperties_test.go
microArch/driver/liquidhandling/serialize.go
microArch/scheduler/liquidhandling/lhrequest.go
microArch/scheduler/liquidhandling/liquidhandling_test.go
microArch/scheduler/liquidhandling/setupagent.go
target/mixer/mixer.go

Make clear what's a tip and what's a tipbox.
Remove some unused vars.

Misc tidying

---

microArch/scheduler/liquidhandling/fixvolumes.go
microArch/scheduler/liquidhandling/fixvolumes_test.go
microArch/scheduler/liquidhandling/layoutagent2.go
microArch/scheduler/liquidhandling/layoutagent_test.go
microArch/scheduler/liquidhandling/liquidhandler.go
microArch/scheduler/liquidhandling/setupagent.go
target/mixer/mixer.go

make it more obvious that functions are impure
loop fusion.

misc fixes again

---

cmd/migrate/doc.go
cmd/migrate/main.go
workflow/v1_2/migrater.go
workflow/v1_2/workflow.go

This works. However it has revealed some oversights with the FileManager, so I shall address those in a different ticket tomorrow.

[ANTHA-2700] Get migrate command to cope with files embedded within the workflow

---

workflow/merge.go

Also annoyed I can't reopen a PR after it's been merged. Stoopid github...

[ANTHA-2739] Address QA. Very annoyed this has cost 1 line more!

---

target/qpcrdevice/qpcrdevice.go

I'm building the new UI for starting the qPCR run.
The old UI looks like this:
The new UI looks like this:
I sat down with Nuno and we came up with this improved message, so that it makes the user experience better, and works with the new UI (e.g. "Click the button below" instead of "Accept").

qPCR: Update message shown in the UI

---

workflow/repositories.go
workflow/validate.go

This also forced me to do some light refactoring and remove some duplication.
Tested with all permutations (both legal and illegal) of repositories.json.

[AC-74] Detect when commit object is not found, and error more helpfully

---

antha/anthalib/wtype/fileseries.go
antha/compile/antha.go
workflow/migrate/params.go

Merged the recent changes from `master` including the `FileSeries` data type definition + changed `File` to `*File` (do I understand right that antha-core uses pointers to files?)

Antha 2772 file series antha core

---

cmd/composer/doc.go
cmd/composer/main.go
scripts/composer-cloud.sh

Update go doc and cloud composer script.

[AC-79] Switch linkedDrivers default to true.
