cmd/antharun/frontend/frontend.go
microArch/logger/default.go
microArch/logger/logger.go
microArch/logger/logger_test.go
microArch/logger/middleware/file/fileMiddleware.go
microArch/logger/middleware/handler/handler.go
microArch/logger/middleware/handler/handler_test.go

Add a Data call to the log library so that we can log arbitrary structs.

Add a Data call to log library

---

antha/anthalib/wunit/wdimension.go
codegen/codegen_test.go
microArch/scheduler/liquidhandling/lhrequest.go
microArch/scheduler/liquidhandling/liquidhandler.go
target/human/inst.go
target/inst.go

target/insts now implement a call for returning a time estimate 
for mixes this is populated via the timer mechanism for liquid handling instructions
for incubates this comes directly from the time parameter 
also contains a trivial bugfix to an error message
prerequisite for same change on microarch

Addtimeestimate

---

antha/anthalib/wtype/lherror.go
antha/anthalib/wtype/lherror_test.go
codegen/codegen_test.go
microArch/driver/liquidhandling/compositerobotinstruction.go
microArch/driver/liquidhandling/lherror_test.go
microArch/driver/liquidhandling/lhpolicy.go
microArch/driver/liquidhandling/lhproperties.go
microArch/driver/liquidhandling/makelhpolicy.go
microArch/driver/liquidhandling/robotinstruction.go
microArch/driver/liquidhandling/robotinstructionset.go
microArch/factory/make_component_library.go
microArch/factory/make_tip_library.go
microArch/scheduler/liquidhandling/executionhelpers.go
microArch/scheduler/liquidhandling/funcs.go
microArch/scheduler/liquidhandling/input_plate_setup.go
microArch/scheduler/liquidhandling/layoutagent2.go
microArch/scheduler/liquidhandling/lherror_test.go
microArch/scheduler/liquidhandling/liquidhandler.go
microArch/scheduler/liquidhandling/make_liquidhandler.go
microArch/scheduler/liquidhandling/newexecutionplanner.go
microArch/scheduler/liquidhandling/setupagent.go
microArch/scheduler/liquidhandling/solution_setup.go
microArch/scheduler/liquidhandling/tip_box_setup.go
target/inst.go
target/mixer/mixer.go

Mostly additions to liquid handling planner code to ensure that errors are passed back to caller instead of creating calls to logger.Fatal
target/Inst now has Error() which returns any error it has received
the only bullet bitten is in the generator for MixInsts -- in order to pass them back to the front end, mix tasks which generate errors now return MixInsts which do not return nil when Error() is called... attempts to look at generated files without checking this is safe will therefore fail

Addplanningerrors

---

microArch/factory/make_plate_library.go

Added riser heights to plate type names
"riser" --> "riser40"
"shallowriser"-->"riser20"
kept old naming scheme in addition for backwards compatibility but should switch to this convention from now on until we fix this properly... pls ensure any other plates with riser but without 'riser' in the name are modified to fit with this convention

Added riser height to plate types

---

microArch/driver/liquidhandling/makelhpolicy.go
microArch/factory/make_plate_library.go

Removed duplicated post mix volume in make LH policy for PEG.
Updated plate heights for SRFWB96 plates on incubator and physically tested

Protoplast newplate input

---

antha/anthalib/wtype/lhcomponent.go
antha/anthalib/wtype/lhplate.go
antha/anthalib/wtype/lhwell.go
antha/anthalib/wtype/platelocation.go
antha/anthalib/wtype/wtype_test.go
microArch/driver/liquidhandling/lhproperties.go
microArch/scheduler/liquidhandling/autoallocate_test.go
microArch/scheduler/liquidhandling/input_plate_setup.go
microArch/scheduler/liquidhandling/layoutagent2.go
microArch/scheduler/liquidhandling/lhrequest.go
microArch/scheduler/liquidhandling/liquidhandler.go

This PR extends autoallocation to anonymous components coming in outside plates.
This may create confusion in some cases but hopefully will be clearer on aggregate.
Limitation: if the component is too big to fit into a single autoallocated well the system will refuse, throw an error, and go sulk in the corner
this may be confusing in some cases since it will work or not depending on what other autoallocated components are in the mix. Hence YMMV.
Please test and see how it goes.

Autoallocate mixes in place

---

microArch/scheduler/liquidhandling/liquidhandling_test.go
microArch/scheduler/liquidhandling/setupagent.go

Tip types specified on command line now override defaults rather than adding to them

Override tip type

---

microArch/factory/make_plate_library.go

Ran plate tests on the new IDT plate:
Residual volume was set at 200ul, which allows efficient aspirating/dispensing after testing. Tips unable to go to bottom of well due to tip head collision, hence high residual volume set. Likely with multichannel use, when implemented, tip head can go much lower
-High volume aspirating and dispensing tested OK
-Low volume aspirating and dispensing tested OK

New plate/idt plate

---

antha/AnthaStandardLibrary/Packages/doe/doe.go

Previous fix resulted in panic if the file was specified as DX

fix doe-return-error-if-incorrect-fileformat

---

cmd/antharun/cmd/run.go
target/mixer/opt.go

Previously was getting squashed by version coming from makeMixerOpt

Moved execution planning version to default options in mixer

---

antha/anthalib/wtype/lhplate.go
microArch/factory/make_plate_library.go
microArch/factory/make_plate_library_test.go

this includes tube racks and gel loading racks

Exceptions for special plate types that can't be multichanneled

---

microArch/driver/liquidhandling/lhproperties.go
microArch/scheduler/liquidhandling/ichain.go
microArch/scheduler/liquidhandling/input_output_state_test.go
microArch/scheduler/liquidhandling/liquidhandler.go

Volume calculations for our 'output plates' should not have 'temporary'
items removed, but rather remove any intermediary wells that would have
been used but aren't relevant to the input or output plates.
If I've followed the code correctly when a component is both temporary and auto-allocated it should represent a non-final well state.

Ensure waste is included in our output plate state

---

cmd/anthafmt/format.go

Giving more comprehensive error message to anthafmt.
It now returns the path to the file in which errors occurs along with the error message.

anthaFmt minor improvement

---

target/mixer/mixer.go
target/mixer/opt.go

Required to allow cleanup of sqlite filenames in trilution.

allow specification of output filename

---

antha/anthalib/wtype/lhcomponent.go
microArch/scheduler/liquidhandling/ichain.go
microArch/scheduler/liquidhandling/liquidhandler.go
microArch/scheduler/liquidhandling/newexecutionplanner.go

Sample should return two components: the sample and the original component, which has now changed. Currently this does not happen.
This feature allows us to use previouslySampledComponent = Mix(previouslySampledComponent) to keep the ID up to date and ensure mixes happen in the correct order
Whether this persists in future is an open question; we might consider postpending this to any sampling that goes on during the transpilation step so that it is transparent to the user. Whether this is preferable to having two returns to Sample is open to discussion.

Support for no-op mixes

---

antha/anthalib/wtype/lhcomponent.go

PolicyName methods added for consistency when writing Antha elements
+ prevent  runtime errors when calling nil concs and volumes from component

PolicyName and SetPolicyName methods, prevent panics

---

inventory/testinventory/make_plate_library.go

See attached document for testing details. 
Overall functions fine. 
Residual volume set at 10 ul (zoffsets dictate there must be some leeway for both the LV and HV tips, hence higher residual volume). Can optimise if needed (minimum 5 ul)
https://www.dropbox.com/s/exqhmbkseppcm31/TwistDNAPlate.docx?dl=0
Passed on to Adam for generation of UI data for plate

added twist dna plate to library following functional testing

---

inventory/testinventory/devices.go
inventory/testinventory/make_plate_library.go
inventory/testinventory/make_plate_library_test.go

Refactored PCR plate holders/coolers to be treated as a riser which have a plateConstraints field to indicate that only certain plates can be added to them.
Added tests which ensure heights of previous plates in the library are maintained. This required the ability to specify SpecialOffsets for a plate/riser combination. This is undesirable but probably necessary since certain tubes will sit differently in a rack depending on the diameter of the tube, and in some cases there is a solid base which ensures all tubes sit at the same height, regardless of the tube diameter.
Untested in lab at present but any previous heights have CI tests added to check the heights are equivalent to before.

Plate library/cooler as incubator

---

inventory/testinventory/make_tip_library.go

Otherwise 30ul tips are (correctly) picked up by the high volume head on
gilson which (incorrectly) causes a crash
Have tested in trilution that this avoids the issue

Reduce maxvol for 30ul filter tips to 20ul

---

execute/intrinsics.go

Rename reagents to reactions

---

antha/anthalib/wtype/tipestimate.go
microArch/scheduler/liquidhandling/count_tips_used.go
microArch/scheduler/liquidhandling/count_tips_used_test.go
microArch/scheduler/liquidhandling/lhrequest.go
microArch/scheduler/liquidhandling/liquidhandler.go
microArch/scheduler/liquidhandling/refresh_tipboxes.go
target/inst.go

This adds a simple count of tips used which is reported via the mix task 
Tip use is counted from the instructions generated using the load tips (LOD) instruction

Reports name, number and tipbox count used

---

microArch/driver/liquidhandling/getComponents.go

0.0001 is elsewhere also used to check for float discrepancies so this
should be in line with other checks.

Workaround for float discrepancies

---

antha/anthalib/wtype/lhwell.go

It wasn't referred to externally, but would likely have caused future confusion

Remove MaxTotalVolume from LHWell, this is now MaxVolume

---

antha/compile/antha.go
cmd/antha/cmd/run.go
cmd/antha/main.go
execute/context.go
execute/error.go
execute/execute.go

`Errorf("some error")` will print `element XXX: some error`.
If you do `fmt.Printf("%+v", err)` you'll get a stack track too. Whether that should be the default, I can handle in a separate PR.

add element name to Errorf messages

---

cmd/antha/cmd/metadata.go
cmd/antha/cmd/metadata_add_tags.go

adds a new subcommand `antha metadata add-tags`.
For example, running
```
antha metadata add-tags MVL
```
will add the tag MVL to all the metadata for elements in the current directory and below.

antha metadata add-tags: initial

---

antha/anthalib/mixer/mixer.go
antha/anthalib/wtype/lhplate.go
microArch/driver/liquidhandling/getComponents.go
microArch/scheduler/liquidhandling/executionhelpers.go
microArch/scheduler/liquidhandling/ichain.go
microArch/scheduler/liquidhandling/liquidhandler.go
microArch/scheduler/liquidhandling/tgraph_test.go

- there was an error when the "stationary" component (i.e. the remainder after sampling) was not used which led to mixes and splits being combined into a single node of the execution graph. This causes downstream issues and so these are now separated into two nodes wherever this happens.
- remainders were also not registering as having locations set if their parent component's location is assigned automatically since these are copies rather than references. Invoking the sample tracker's ID-forwarding mechanism during the SplitSample command definition was sufficient to get the right behaviour.

Fixes to splitsample

---

antha/AnthaStandardLibrary/Packages/buffers/order/order.go
antha/AnthaStandardLibrary/Packages/eng/Evaporation.go
antha/AnthaStandardLibrary/Packages/sequences/kmer/kmer_test.go
antha/AnthaStandardLibrary/Packages/sequences/parse/genbank/genbank_parser.go
antha/AnthaStandardLibrary/Packages/sequences/parse/genbank/genbankparser_test.go
antha/anthalib/wtype/biology.go
antha/anthalib/wtype/lhplate_test.go
antha/anthalib/wtype/shape.go
antha/anthalib/wunit/conversion.go
driver/lh/client_test.go
microArch/driver/liquidhandling/transferblock_test.go
microArch/driver/liquidhandling/transferparams.go
microArch/logger/logger_test.go
microArch/scheduler/liquidhandling/liquidhandler.go
microArch/scheduler/liquidhandling/solution_setup.go
microArch/scheduler/liquidhandling/tgraph_test.go
microArch/simulator/liquidhandling/simulator_testcode_test.go

fixes build errors in golang1.10
Main cause of changes is that fmt.Printf/Sprintf without format codes, or fmt.println without now generates compile errors
Bigger changes to StorageConditions.String() - golang1.10 detects the loop and raised a compile error

Fixes for golang 1.10

---

antha/anthalib/wtype/functions.go
antha/anthalib/wtype/geometry.go
microArch/driver/liquidhandling/tipswellsaligned.go
microArch/driver/liquidhandling/tipswellsaligned_test.go
microArch/driver/liquidhandling/transferblock_test.go
microArch/driver/liquidhandling/transferinstruction.go

Two things
1) refactoring tip/well alignment checks used by multichannel planning to have a better signature: now depends on robot type, head of robot to be used, plate type and wells to be addressed
2) explicitly checking for clashes using well geometry for nonstandard plate types
rolling this out further and getting max efficiency in the case of, e.g., big wells has to be left as part of another story as it has several considerations. Hence one test is now deprecated and skipped pending picking up this subsequent story.

Refactor of tip/well alignment checks

---

microArch/driver/liquidhandling/choosechannel.go
microArch/driver/liquidhandling/choosechannel_test.go
microArch/driver/liquidhandling/compositerobotinstruction.go
microArch/driver/liquidhandling/lhl_test.go
microArch/scheduler/liquidhandling/liquidhandling_test.go

Fixes [ANTHA-1278](https://synthace.atlassian.net/browse/ANTHA-1278)
TLDR; Volume rounding was allowing channels whose minimum volume was 0.5ul to pipette less - down to 0.25ul - which ends up causing errors in trilution because the machine can't pipette less than 0.5ul
Choose channels now explicitly checks that requested volume is greater than the minimum possible, to within rounding error.

Prevent attempts to pipette small volumes

---

antha/anthalib/wtype/LiquidType.go

This was missing, resulting in, for example, `nil` labels coming up for liquid policy on the UI.

Added LTDNACELLSMIXMULTI to func LiquidTypeName in LiquidType.go

---

antha/AnthaStandardLibrary/Packages/solutions/ContainsComponent.go
antha/AnthaStandardLibrary/Packages/solutions/normaliseName.go
antha/AnthaStandardLibrary/Packages/solutions/normaliseName_test.go
antha/AnthaStandardLibrary/Packages/solutions/subcomponents.go
antha/AnthaStandardLibrary/Packages/solutions/subcomponents_test.go
antha/anthalib/wunit/interface.go
antha/anthalib/wunit/wdimension.go

Fixes issue with component names with concentrations being misleading when several mix steps occur:
relates to: https://repos.antha.com/antha-ninja/elements-westeros/merge_requests/346/diffs

normalise the component name with subcomponents

---

microArch/driver/liquidhandling/transferblock.go
microArch/driver/liquidhandling/transferblock_test.go

Instruction aggregation mistakenly excluded single channel instructions 
Proposed fix for 1259

Moved aggregation to proper place

---

antha/anthalib/wtype/componentvector.go
antha/anthalib/wtype/lhcomponent.go
microArch/driver/liquidhandling/getComponents.go
microArch/scheduler/liquidhandling/fixvolumes.go

This time I definitely ran it though antha-tester and it passed.
key change is in `AllVolsPosOrZero()` in file driver/liquidhandling/getComponents.go - the issue is as we suspected, the carryVol was protecting us from numerical instabilities that we're now exposed to. I played around with matching volumes in matchComponents as well, but it added extra complexity that wasn't actually necessary

Accept sources which are only smaller due to numerical error

---

antha/anthalib/wtype/lhcomponent.go
antha/anthalib/wtype/lhplate.go
antha/anthalib/wtype/lhwell.go
cmd/antha/cmd/run.go
inventory/cache/cache.go
inventory/cache/plateCache/plateCache.go
inventory/cache/plateCache/plateCache_test.go
microArch/driver/liquidhandling/getComponents.go
microArch/driver/liquidhandling/transferblock_test.go
microArch/driver/liquidhandling/transferinstruction.go
microArch/scheduler/liquidhandling/liquidhandler.go
microArch/scheduler/liquidhandling/liquidhandling_test.go

add a cache of temporary plates for use during compilation to save cpu and mem by not having to make a bunch of them
Have tested this with `antha-tester`, though a few changes are required to runner, see branch `plateCache` in antha-runner

Plate cache

---

inventory/testinventory/make_tip_library.go

This prevents crashes to well bottoms when using this tip type

Increased effective tip length

---

antha/anthalib/wtype/lhtip.go
microArch/simulator/liquidhandling/simulator.go
microArch/simulator/liquidhandling/simulator_test.go

simulator tests that inexplicit dispenses can't happen when channels aren't independent (e.g. when DSP from channel 0 would cause DSP from channel1)

Fix: dispense command

---

antha/anthalib/wtype/makelhpolicy.go

where ASPSPEED and DSPSPEED are the same we should set DEFUALTPIPETTESPEED instead since he speed will then be inherited if any PRE or POST MIX is set. 
In particular, this was  found to be a problem when using the protoplasts policy and setting a POST MIX in an element.

use DEFUALTPIPETTESPEED rather than ASP and DSP

---

antha/anthalib/wtype/aparam.go
antha/anthalib/wtype/makelhpolicy.go
microArch/driver/liquidhandling/compositerobotinstruction.go
microArch/driver/liquidhandling/lhpolicytestframework_test.go
target/mixer/mixer.go

- This increases the default speeds of pipetting to maximum of 3.7ml/min on a low volume head and 37ml/min on the high volume head.
- Any policy without a default speed set explicitly in the policy will be increased to maximum for the appropriate head. 
- System Policies have been updated to ensure the defaults will be applied appropriately, and robust to cases where they are modified in elements.
- Z movement speed has also been increased to 140

ANTHA-1829: turn things up to 37

---

antha/anthalib/wtype/makelhpolicy.go

Mix rate should be inherited from Default pipette speed in most cases

turn off mix rate where default pipette speed is not set

---

antha/anthalib/wtype/makelhpolicy.go

ASPREFERENCE and DSPREFERECE are overridden by USE_LLF, and don't cause liquid level following on their own

Small fix to LLF policies

---

microArch/driver/liquidhandling/convertinstructions.go

Tests still pass, and code coverage verifies this function is being hit.

Simplify code.

---

antha/anthalib/wtype/aparam.go

This is just a consequence of me reading code and seeing things that can be tidied a little. If this is not helpful that please say and we can just throw this away completely.
By using literal maps, and moving away from strings a bit, the code is a bit clearer to read, and it caught a bug too (ASPREFERENCE was defined twice (line 80 and line 125)).

Simplify declaration of aparams.

---

microArch/scheduler/liquidhandling/executionhelpers.go
microArch/scheduler/liquidhandling/executionhelpers_test.go
microArch/scheduler/liquidhandling/liquidhandler.go
microArch/scheduler/liquidhandling/tgraph.go
microArch/scheduler/liquidhandling/tgraph_test.go

Building the topological graph can now fail if SplitSample is used incorrectly. This change returns error instead of calling panic

Don't Panic() when building the instruction graph fails, return error instead

---

antha/anthalib/wtype/lhtypes.go

This PR adds a couple of useful things to adaptors
- the ID field is now used and maintained on duplication / reassigned depending on option
- adaptors now define a method to declare a "type" based on their manufacturer and model

Add ID and AdaptorType methods to aid adaptor identification

---

inventory/testinventory/make_tip_library.go
inventory/testinventory/make_tip_waste_library.go
microArch/scheduler/liquidhandling/setupagent.go

Previously represented this as the gilsontipwaste (i.e. the on deck box) but this is considerably taller than the chute and so several collisions are predicted with the box which do not occur when using the chute

use the gilson tip chute by default

---

microArch/simulator/liquidhandling/errors.go

Previously, CollisionError would generate a helpful string description of the error only when Error() was called. This is now invalid since the state will now change as the simulation proceeds and we try to catch as many errors as possible.
Another possible solution would have been to duplicate the entire state for the error, but this seemed unnecessary since all the required information is available at the time of the error.
Have run antha-tester with no errors

Generate collision descriptions at the time of the error

---

cmd/antha/cmd/convert_all_bundle_parameters.go
cmd/antha/cmd/convert_bundle_parameters.go
workflow/workflow.go

Designed to facilitate automated upgrading of element bundles based on a defined mapping.
For example, running the command with the following metadata file against a test bundle would upgrade `Aliquot` to `Aliquot_Liquid` and  the output `Aliquots` would be updated to `NewLiquids` and the input `Solution` to `Liquid`.
```
{
"defaults": {
"ByRow": false,
"NumberofAliquots": 8,
"OutPlate": "SRWFB96_riser18",
"Solution": "water",
"VolumePerAliquot": "50ul"
},
"name": "Aliquot",
"tags": [
"MVL"
],
"new-element-mapping-details":{
"new-element-name": "Aliquot_Liquid",
"new-parameter-mapping": {
"Aliquots": "NewLiquids",
"Solution": "Liquid"
},
"old-element-name": "Aliquot"
}
}
``` 
Tested locally and working as expected.

cmd to update bundle file based on mapping details from metadata file

---

antha/compile/compile.go

As reported by Xander, the line numbers were off by 1 (or 2, in some places), a feature which managed to slip through both original testing and QA.
Upon closer inspection of the transpiler, we only ever call writeString for Go/Antha, and writeByte is only called for comments and whitespace. Now as whitespace does include the initial line indentation, it was still being called for every line. However, the correct internal position token isn't updated until the token itself is printed, which is after the indentation. So when we were in writeByte, I think the internal source position was still at the previous token, rather than the next.
Anyway, moving the line number catching into writeString seems to solve this issue.
cc @x-anderson

Fix creation of line number map.

---

antha/anthalib/wtype/tipestimate.go
microArch/scheduler/liquidhandling/liquidhandler.go

Showing tip usage on the command line along with deck setup info, and also print low level instructions (when --printInstructions is set) before the physical simulation so they get printed even when the physical simulation fails

Showing tip use on the command line

---

cmd/antha/cmd/run.go

Small fix to prevent test annotations to bundles making them unreadable
I have tested this by making 18 bundles and running them through the CI pipeline and also by manual testing - which are both successful

Use marshalindent

---

microArch/scheduler/liquidhandling/layoutagent2.go

make error message more actionable rather than: 
```
2018-08-07 17:05:15STEP 3/3: Failed
2018-08-07 17:05:15error planning: 8 (LH_ERR_DIRE) : an internal error : MIX IN PLACE WITH NO LOCATION SET
```

include liquid name in error message

---

execute/error.go
execute/execute.go

Before:
```
> antha run --driver go://github.com/Synthace/PipetMaxDriver/server --bundle ~/Downloads/1x\ Aliquot\ \(3\).json 
0 server Listening at [::]:38945
error: element Aliquot: Aliquot volume specified (500 ul) too high for well capacity (340 ul) of current plate (SRWFB96_riser18_e553f1d-e490-416b-914a-1155390f46)
goroutine 1 [running]:
runtime/debug.Stack(0x2, 0xc400000073, 0x415618)
/home/matthew/src/golang/go1.10.3/src/runtime/debug/stack.go:24 +0xa7
github.com/antha-lang/antha/inject.ElementStackTrace(0xc4209f7ce0, 0x12a4dc0)
/home/matthew/src/Go_external_1.10.3/src/github.com/antha-lang/antha/inject/linemap.go:45 +0x37
github.com/antha-lang/antha/execute.Run.func1(0xc4209f8ac8)
/home/matthew/src/Go_external_1.10.3/src/github.com/antha-lang/antha/execute/execute.go:57 +0x57 …
```

[ANTHA-1989] For a user error, no stack trace.

---

microArch/driver/liquidhandling/timerfactory.go

Some log parsing and filtering revised my timing estimates quite a bit. 
In general the original values were tolerably close for the large-scale actions (SUK,BLW etc.) but the others were a compromise and have mostly been decreased. The most notable change is that the MIX command has been dropped by 75%, which is a relief since this was causing the biggest changes.

Updated times based on data from trilution logs for ~450 runs

---

microArch/scheduler/liquidhandling/liquidhandler.go

Time estimates are currently subject to the same floating point overprecision in the front-end as volumes. This is since the move to more accurate estimates, which include fractions of seconds.
Previously we didn't see this so I hope that rounding to the nearest second as here will solve the problem.
I've tested this on the command-line, although without the front-end it's impossible to see if it really fixes the problem

round to nearest second

---

codegen/codegen.go
codegen/codegen_test.go
codegen/instgraph.go
target/handler/generic.go
target/inst.go
target/mixer/mixer.go
target/platereader/platereader.go
target/qpcrdevice/qpcrdevice.go
target/shakerincubator/shakerincubator.go

Introduce an AppendDependsOn method to simplify a number of uses of the current SetDependsOn.
Local tests and antha-runner tests pass as before.

[ANTHA-2031] Improve the target.Inst interface

---

antha/anthalib/wunit/wunit.go

We have versions which return the new measurement and an error, but often the caller can be certain that there won't be an error (e.g. when converting volumes, since all volume units are compatible) so it tidies up the call sites significantly to have `Must` variants which panic instead of returning error

[ANTHA-2057] Add MustIn[String]Unit variants to ConcreteMeasurement

---

antha/anthalib/mixer/mixer.go
antha/anthalib/wtype/lhinstruction.go
execute/intrinsics.go
microArch/driver/liquidhandling/convertinstructions.go
microArch/driver/liquidhandling/lhivector.go
microArch/driver/liquidhandling/splitblock.go
microArch/driver/liquidhandling/transferblock.go
microArch/driver/liquidhandling/transferblock_test.go
microArch/scheduler/liquidhandling/autoallocate_test.go
microArch/scheduler/liquidhandling/determinism_test.go
microArch/scheduler/liquidhandling/executionhelpers.go
microArch/scheduler/liquidhandling/executionhelpers_test.go
microArch/scheduler/liquidhandling/fixvolumes.go
microArch/scheduler/liquidhandling/fixvolumes_test.go
microArch/scheduler/liquidhandling/getinputs.go
microArch/scheduler/liquidhandling/ichain.go
microArch/scheduler/liquidhandling/ichain_test.go
microArch/scheduler/liquidhandling/input_output_state_test.go
microArch/scheduler/liquidhandling/layoutagent2.go
microArch/scheduler/liquidhandling/lhrequest.go
microArch/scheduler/liquidhandling/liquidhandler.go
microArch/scheduler/liquidhandling/liquidhandling_test.go
microArch/scheduler/liquidhandling/setupagent.go
microArch/scheduler/liquidhandling/solution_setup.go
microArch/scheduler/liquidhandling/tgraph.go
microArch/scheduler/liquidhandling/tgraph_test.go
target/mixer/mixer.go

Not sure what to do about AddComponent: I'm happy to change it to AddInput, but there are 3 elements that I can find that use it (Transformation, Setup_Input_Plate, Transformation_Multi). Just fearful of changing a public API that may be used by 3rd party elements - how do we normally handle this case?
NB: this PR is entirely find and replace, with the exception of lhinstruction.go itself.
Local tests pass. Just running through antha-tester now...

Unify LHInstruction.Add{Product,Result} into .AddOutput.

---

antha/anthalib/mixer/mixer.go
execute/execute.go
execute/intrinsics.go
microArch/driver/liquidhandling/lhproperties.go
microArch/sampletracker/context.go
microArch/sampletracker/sampletracker.go
microArch/sampletracker/sampletracker_test.go
microArch/scheduler/liquidhandling/autoallocate_test.go
microArch/scheduler/liquidhandling/input_output_state_test.go
microArch/scheduler/liquidhandling/input_plate_setup.go
microArch/scheduler/liquidhandling/layoutagent2.go
microArch/scheduler/liquidhandling/layoutagent_test.go
microArch/scheduler/liquidhandling/liquidhandling_test.go
target/mixer/mixer.go

Previously the SampleTracker was a global variable which prevented parallel execution/simulation of workflows. 
This PR creates a new SampleTracker stored in the context in `execute.Run` so that each thread has a different sample tracker. Each instance where the global SampleTracker was used is then replaced by fetching the sample tracker from the context. `microArch/driver/liquidhandling/GetLocTox` was removed entirely as it is no longer used.
One other change of note is that previously `antha/anthalib/mixer/mixer.SplitSample` was responsible for recording the change of ID in the SampleTracker. Since functions in `mixer` don't have access to the `context` object they can't access the SampleTracker, and so the call to SampleTracker was pushed up to `execute/SplitSample`, which is …

[Antha-2123] store SampleTracker in context object

---

antha/anthalib/wunit/parse.go
antha/anthalib/wunit/unitfromstring.go
antha/anthalib/wunit/unitfromstring_test.go
antha/anthalib/wunit/wunit.go

I noticed that simulation times were really large for workflows with lots of DOE. CPU profiling indicated that we were spending a great deal of time (circa 50% of total in some cases) in `wunit.ParseConcentration`. 
This change simplifies the implementation of the function and more clearly defines its behaviour, extending the test cases to cover units like "% w/v" in the process.
For the bundle used during testing (the one attached to [ANTHA-1947](https://synthace.atlassian.net/browse/ANTHA-1947) ) simulation time is reduced from
```
real	2m4.954s
user	3m10.324s
sys	0m5.274s
```
to 
```
real	0m29.050s
user	0m43.102s
sys	0m3.842s
```
I'm running antha-tester right now, will post results

Overhaul ParseConcentration

---

.travis.yml
antha/AnthaStandardLibrary/Packages/enzymes/Assemblydesign.go
antha/anthalib/mixer/subcomponents_test.go
cmd/antha/cmd/run.go

differences between gofmt in 1.9 vs 1.11 cause linting failures; this prevents those issues

travis to go 1.11, gofmt -s appropriate to this change in 2 files

---

microArch/scheduler/liquidhandling/autoallocate_test.go
microArch/scheduler/liquidhandling/planning_test.go

The test TestInPlaceAutoAllocate is meant to test the following behaviour
- auto-allocate component A
- auto-allocate component B
- mix component B onto A "in-place" - i.e. on top of
However in reality we just move component B to another (unrelated location). This wasn't caught because we were just checking the auto-allocation, not that the mix was happening correctly.
Since this behaviour is not an immediate priority, it was decided to skip the test pending further work to support this case.

Disable TestInPlaceAutoAllocate

---

antha/AnthaStandardLibrary/Packages/enzymes/Ligation.go

Currently the more comprehensive assembly validation function (`FindAllAssemblyProducts`) tests all part order combinations; this is thorough and more powerful at detecting potential mis assemblies but is very computationally expensive hence there exists a threshold number of parts above which the simpler assembly validation will occur which will only test the validity of the assembly in the part order specified. 
The threshold is currently set to 7 part assemblies (6 parts + vector) which is 7! (5040) part order combinations. In practice this is too computationally expensive to run on multiple assemblies; this PR therefore reduces the threshold to 5 part assemblies (4 parts + vector, 5! = 120) which we know simulates fine with the more comprehensive assembly validation.

Antha-2292: only attempt all part combinations for <= than 5 part assemblies

---

ast/ast.go
ast/inst.go
cmd/antha/pretty/run.go
cmd/antha/pretty/timeline.go
codegen/codegen.go
codegen/codegen_test.go
codegen/implicit.go
codegen/instgraph.go
execute/execute.go
target/auto/auto.go
target/auto/execute.go
target/auto/pretty.go
target/device.go
target/graph.go
target/handler/generic.go
target/handler/handler.go
target/human/human.go
target/inst.go
target/mixer/mixer.go
target/qpcrdevice/qpcrdevice.go
target/shakerincubator/shakerincubator.go
target/target.go
target/woplatereader/woplatereader.go

To do this has required moving Inst and Device from target to ast in order to avoid an import cycle.
In fact, I rather suspect that the reason ast.Command.Output was interface{} was solely to break the import cycle, which is a bit crazy.
I'm trying to keep these PRs as short as possible. So this PR doesn't actually make trace serializable, but it's a step in that direction.
Test plan:
antha> go build ./...
works.

Give inst.Output a concrete type as it's only used in one place.

---

ast/ast.go
codegen/codegen.go
codegen/codegen_test.go
execute/intrinsics.go

We never make use of the fact this can be a list.
I'm trying to get this whole area of the code simpler and more obvious to better understand what we need before figuring out larger changes to it.
go test -v ./... still works, as does test-bundles.

ast.Command.Request never needs to be plural

---

antha/anthalib/wtype/liquid.go
execute/maker.go
microArch/driver/liquidhandling/convertinstructions.go
microArch/scheduler/liquidhandling/executionhelpers_test.go

Required semantics are set-semantics, so do that!
go test -v ./... passes, and antha-runner test bundles also passes as before.
Motivation: working through maker.MakeNodes and came across strange strings.Split code.

Avoid very strange string munging for Liquid daughtersID

---

antha/compile/antha.go
cmd/antha/cmd/compile.go

add failing file name and problem parameter to error message when antha compile fails due to duplicate parameter specification

return actionable error message

---

antha/anthalib/wtype/lhwell.go
antha/anthalib/wtype/plate.go

Context: Plates seem odd. They're in wtype and thus seem available to elements, but are sorta managed through sampletracker which is in microArch...
I was trying to figure out if we can drop all pointers to Liquids and just pass around maps from ids to objects, which would at least move us away from the weirdness of Dup with IDs (I found some elements that call Dup()...)
Which then made me think of Plates, which contain Wells, which contain Liquids... so I was looking at Wells and came across the protect stuff.

LHWell .Protect is not used.

---

.travis.yml

Go 1.11 has a linter bug (https://github.com/golangci/golangci-lint/issues/148) which results in a fake warning message which breaks feature/datatable branch build

switching to Go 1.11.5

---

antha/anthalib/wunit/unit.go

Instead of triggering a nil pointer error, the methods will return an empty variable.
Please check the differences and feel free to change how this was done.
Beware, that there will be **no** error anymore if someone forgets to enter units. Is that preferable? Perhaps we should just implement a UI check.

ANTHA-2518: Empty return if units is missing.

---

antha/anthalib/wtype/biology.go
antha/anthalib/wtype/wtype_test.go

Currently `wtype.Comp` silently ignores unrecognised characters.
This leads to output that is shorter than input if there are unrecognised characters in the input.
Separately, it would be handy if some non-DNA characters for example `-` (gap) and `.` (match) were passed through.  Then gapped alignments could be reverse-complemented: a useful extension.
The following changes could be made:
1. raise error if a character is not a recognised nucleotide
2. allow specific extra non-DNA characters - an extended alphabet ([this list of IUPAC codes](http://www.bioinformatics.org/sms2/iupac.html]) allows both `-`and `.`)
3. pass through any unrecognised characters unmodified 
Option 1 may have a big impact. There is code to validate nucleotides in `wtype` but validation is not enforced and may not …

Handle unrecognised characters in complement

---

workflow/testing.go
workflow/v1_2/migrater.go
workflow/workflow.go

How does this look for migrating the testing information? Although we have a few other fields in the old workflow none have practical application (either ignored, or switch whether to compare output or instructions - but seems sensible just to compare whichever we're supplied with...)

Basic migration of the test information.

---

scripts/cloud.sh
scripts/composer-cloud.sh

This sets up `composer` to conform to our ambassador sidecar using well-known paths, so we can run it in the simulations cluster with access to content provided via GCS, and uploaded back to datarepo.
See https://paper.dropbox.com/doc/antha-core-workloads-and-git--AbVQgS3DcRoYLEVIGWjNQuixAg-4NDehisKdv1P0MJfah64n for how this will be invoked.

ANTHA-2635 migrate to composer-cloud.sh 

---

workflow/v1_2/config.go
workflow/v1_2/migrater.go

Includes user LH policies in migrated workflows. With this change, the test plan from AC-57 completes without error.
```sh
$ cat /tmp/AC-57/wf/workflow/workflow.json | jq '.Config.GlobalMixer.customPolicyRuleSet'
```
Result:
```json
{
"Policies": {
"DNALV": {
"POST_MIX": 1,
"POST_MIX_RATE": 3,
"POST_MIX_VOLUME": 5,
"POST_MIX_Z": 0.5,
"RESET_OVERRIDE": true,
"TOUCHOFF": false
},
"Needtomix LLD": {
"ASPREFERENCE": 2,
"ASPZOFFSET": -0.5,
"BLOWOUTOFFSET": 0,
"BLOWOUTREFERENCE": 1,
"BLOWOUTVOLUME": 50,
"BLOWOUTVOLUMEUNIT": "ul",
"CAN_MSA": false,
"CAN_MULTI": true,
"CAN_SDD": true,
"DEFAULTPIPETTESPEED": 3.7,
"DEFAULTZSPEED": 140,
"DESCRIPTION": "Needtomix LLD v1",
"DONT_BE_DIRTY": true,
"DSPREFERENCE": 0,
"DSPZOFFSET": 0.5,
"JUSTBLOWOUT": false,
"LLFABOVESURFACE": 3,
"LLFBELOWSURFACE": 3, …
```

[AC-57] Include XLSX-encoded liquid handling policies in migrated workflows

---

antha/AnthaStandardLibrary/Packages/schemas/datainfo.go
antha/AnthaStandardLibrary/Packages/schemas/doc.go
antha/AnthaStandardLibrary/Packages/schemas/parquetinfo/parquetinfo.go
antha/AnthaStandardLibrary/Packages/schemas/parquetinfo/parquetinfo_test.go
antha/anthalib/data/parquet/filemeta.go
antha/anthalib/data/parquet/parquet_test.go
antha/anthalib/data/parquet/reader.go
antha/anthalib/data/parquet/writer.go

The use case for this is adding antha-specific JSON document into the footer.  documentation on the expected usage here: https://paper.dropbox.com/doc/Empirical-data-schemas--Ab8UyJdC2_NJJPkjMEPsY4vlAg-RvV9MPtb5vRwFCvuSIGEM
As part of this, we are no longer redundantly seeking in the file (in reader).

ANTHA-2747 Add parquet metadata support to data tables.

---

Dockerfile
README_Dockerfile.md
cloudbuild.yaml

Slight changes to the Dockerfile and Cloudbuild around the handling of .netrc
Document the whole thing.

[AC-67] Make building the docker image locally possible

---

composer/compile.go
composer/composer.go
composer/transpiler.go
laboratory/effects/filemanager.go
laboratory/laboratory.go
laboratory/testlab/testing.go
target/mixer/base.go
utils/errors.go
utils/file.go
workflow/repositories.go
workflow/workflow.go

In a large number of places we create files and then write to them. We expect those files to not already exist, which means we should be doing O_CREAT|O_EXCL, which we were not.
Additionally, we were using 0400, 0600 and 0700 as the mode to set on the created files. This is awkward: we should be using the defaults (which I believe are 0444, 0666 and 0777) and then relying on the system imposing the user's umask (typically 0022) to reduce those.
Testing:
The normal `rm -rf /tmp/foobar && ./composer -outdir /tmp/foobar -keep -linkedDrivers repositories.json workflow3.json.sample gilsonOnly.json.sample` works before and after with sensible permissions appearing.
Setting umask to 0077 and rerunning does correctly reduce the mode of the created files.

[AC-71] Reform file creation

---

antha/anthalib/wtype/plate.go
antha/anthalib/wtype/plate_test.go
workflow/simulaterequestpb/provider.go

antha-runner/aconv already contains converters from inventory plates
and plate types into the antha-lang versions, however the new
PlateType class is not supported.
Since it seems reasonable enough to have a method to extract a plate
type back out of a plate the conversion now works by creating a plate
from the inventory Plate Type then extracting the plate type from it.
I added a basic unit test which demonstrates that the extracted plate
type is fine for making another plate of the same type with, and equal
to the one which was used in the first place.

Convert plate types from inventory protobuf

---

cmd/composer/doc.go
cmd/composer/main.go
cmd/elements/defaults.go
cmd/elements/describe.go
cmd/elements/doc.go
cmd/elements/list.go
cmd/elements/makeworkflow.go
cmd/migrate/doc.go
cmd/migrate/main.go
composer/doc.go
workflow/readers.go
workflow/workflow.go

The existing docs are actually pretty reasonable, with one or two oversights.
What's mainly missing is pointers to those docs from the command -h form. So address that.
And generally review and polish all documentation.

[AC-78] Generally improve all command documentation.
